AWSTemplateFormatVersion: 2010-09-09
Description: S3 bucket for Lambda artifact

Parameters:
  application:
    Default: kalinchih-my-ip
    Type: String

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: project
          Value: !Sub "${application}"
        - Key: env
          Value: dev
      BucketName: !Sub "${application}-artifact"
      AccessControl: BucketOwnerFullControl
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
