AWSTemplateFormatVersion: 2010-09-09
Description: CloudFront for Serverless API

Parameters:
  application:
    Default: kalinchih-my-ip
    Type: String

  apiDomainName:
    Default: 3uzizhoukf.execute-api.ap-northeast-1.amazonaws.com
    Type: String

Resources:
  ApiCloudfront:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      Tags:
        - Key: project
          Value: !Sub "${application}"
        - Key: env
          Value: dev
      DistributionConfig:
        Origins:
          - DomainName: !Sub "${apiDomainName}"
            Id: ApiOrigin
            CustomOriginConfig:
              HTTPPort: "80"
              HTTPSPort: "443"
              OriginProtocolPolicy: https-only
            OriginCustomHeaders:
              - HeaderName: "myip-authtoken"
                HeaderValue: "AuthTokenFromCloudFront"
        Enabled: "true"
        HttpVersion: "http2"
        DefaultCacheBehavior:
          Compress: true
          AllowedMethods:
            - "GET"
            - "HEAD"
            - "OPTIONS"
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          TargetOriginId: ApiOrigin
          ViewerProtocolPolicy: redirect-to-https
          DefaultTTL: 0
          MaxTTL: 0
          MinTTL: 0
        IPV6Enabled: false
