AWSTemplateFormatVersion: 2010-09-09
Description: View bucket with CloudFront

Parameters:
  application:
    Default: kalinchih-my-ip
    Type: String

Resources:
  ViewBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${application}-view"
      AccessControl: BucketOwnerFullControl
      VersioningConfiguration:
        Status: Enabled

  ViewBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: ViewBucketPolicy
        Statement:
          - Sid: 1
            Effect: Allow
            Principal:
              CanonicalUser:
                Fn::GetAtt:
                  - ViewCloudfrontOriginAccessIdentity
                  - S3CanonicalUserId
            Action: s3:GetObject
            Resource:
              Fn::Join:
                - ""
                - - "arn:aws:s3:::"
                  - Ref: ViewBucket
                  - "/*"
      Bucket:
        Ref: ViewBucket

  ViewCloudfront:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub "${application}-view.s3.amazonaws.com"
            Id: ViewBucket
            S3OriginConfig:
              OriginAccessIdentity: !Join
                - ""
                - - "origin-access-identity/cloudfront/"
                  - !Ref "ViewCloudfrontOriginAccessIdentity"
        Enabled: "true"
        HttpVersion: "http2"
        DefaultCacheBehavior:
          AllowedMethods:
            - "GET"
            - "HEAD"
            - "OPTIONS"
          Compress: false
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
          TargetOriginId: ViewBucket
          ViewerProtocolPolicy: redirect-to-https
          DefaultTTL: 0
          MaxTTL: 0
          MinTTL: 0
        IPV6Enabled: false

  ViewCloudfrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "${application}-view OriginAccessIdentity"
